#!/usr/bin/env ruby
require 'rbvmomi'
require 'optparse'

host = String.new
user= String.new
password= String.new
datacenter_name= String.new
target_name= String.new
max_usage=0

OptionParser.new do |opts|
	opts.on("-H=HOST", "--host=HOST", "vCenter host") do |H|
		host = h
	end
	opts.on("-u=USER", "--user=USER", "vCenter username") do |u|
		user = u
	end
	opts.on("-p=PASS", "--password=PASSWORD", "vCenter password") do |p|
		password = p
	end
	opts.on("-d=DATACENTER", "--datacenter=DATACENTER", "Datacenter of target") do |d|
		datacenter_name = d
	end
	opts.on("-s=DATASTORE", "--target=DATASTORE", "Datastore to monitor") do |s|
		target_name = s
	end
	opts.on("-w=WARNING", "--warning=WARNING", "Warning threshold (%)") do |m|
		warning = w.to_i
	end
	opts.on("-c=CRITICAL", "--critical=CRITICAL", "Critical threshold (%)") do |m|
		critical = c.to_i
	end
end.parse!
begin
	vim = RbVmomi::VIM.connect host: host, user: user, password: password, :insecure => true
	dc = vim.serviceInstance.find_datacenter(datacenter_name)

	target =  dc.datastoreFolder.children.select{|ds| ds.name == target_name}.first
	$status="OK"
	$exitcode=0
	$free_space=target.summary.freeSpace.to_f
	$capacity=target.summary.capacity.to_f
	begin
		if defined? target.children
			target.children.each do |ds|
				if ds.summary.accessible == false
					$status="CRITICAL"
					$exitcode=2
				end
			end
		else
			if target.summary.accessible == false
				$status="CRITICAL"
				$exitcode=2
			end
		end

		if ((target.summary.capacity.to_f - target.summary.freeSpace.to_f)/target.summary.capacity.to_f)*100 >= warning and $status == "OK"
			$status="WARNING"
			$exitcode=1
		end
		if ((target.summary.capacity.to_f - target.summary.freeSpace.to_f)/target.summary.capacity.to_f)*100 >= critical and $status == "OK"
			$status="CRITICAL"
			$exitcode=2
		end
	rescue
		if not target.accessible
			$status="CRITICAL"
			$exitcode=2
		end
	end
rescue
	$status="UNKNOWN"
	$exitcode=3
end
$utilization = (($capacity.to_f-$free_space.to_f)/$capacity.to_f)*100
puts "DATASTORE #{$status} - free space #{$free_space}/#{$capacity}; | used=#{$utilization}%;#{warning};#{critical}"
exit $exitcode
