#!/usr/bin/env ruby

require 'rubygems'
require 'openvpn_management'
require 'pp'
require 'trollop'

opts = Trollop::options do
	opt :Host, "Target host", :type => :string
	opt :port, "Target Port", :type => :integer
	opt :password, "Openvpn Management password", :type => :string
end

vpn_server = OpenvpnManagement.new :host => opts[:Host], :port => opts[:port], :password => opts[:password]
routes = vpn_server.status[:routes].keys.count
vpn_server.destroy

@code = 0
@status = "OK"

puts "ROUTES #{@status} - #{routes} "

if routes <= 11
	@code = 2
	@status = "CRITICAL"
end

exit @code

