#!/usr/bin/env	ruby

require 'snmp'
require 'trollop'

opts = Trollop::options do
	opt :critical, "Critical threshold in MB", :type => :integer, :default => 512
	opt :warning, "Warning threshold in MB", :type => :integer, :default => 1024
	opt :Host, "Target host", :type => :string
	opt :community, "Community string", :type => :string
end

snmp = SNMP::Manager.new(:host => opts[:Host], :community => opts[:community])
res = snmp.get(["1.3.6.1.4.1.2021.4.15.0"])
cache = res.vb_list.first.value.to_i

res = snmp.get(["1.3.6.1.4.1.2021.4.14.0"])
buffer = res.vb_list.first.value.to_i

res = snmp.get(["1.3.6.1.4.1.2021.4.6.0"])
real_free = res.vb_list.first.value.to_i
snmp.close

free = ((real_free + buffer + cache)/1024)

@code = 0
@status = "OK"

if free <= opts[:warning]
	@code = 1
	@status = "WARNING"
end
if free <= opts[:critical]
	@code = 2
	@status = "CRITICAL"
end


puts "MEMORY #{@status} - #{free} MB Free|free=#{free}mb;#{opts[:warning]};#{opts[:critical]}"
